#!/bin/sh
die() {
	echo $0: $1
	exit 1
}

set_app_uidgid() {
	echo "$APP_UID" | grep -q '[^0-9]' && die "APP_UID is not a number: '$APP_UID'"
	echo "$APP_GID" | grep -q '[^0-9]' && die "APP_GID is not a number: '$APP_GID'"
	APP_UID=$(( APP_UID ))
	APP_GID=$(( APP_GID ))
	if test $APP_UID -eq 0; then
		APP_UID=$( stat -L -c %u "$VOLUME_DIR" )
		APP_GID=$( stat -L -c %g "$VOLUME_DIR" )
	fi
	if test $APP_UID -eq 0; then
		APP_UID=$(( RANDOM + 10000 ))
		APP_GID=$APP_UID
	fi
}

VOLUME_DIR=${VOLUME_DIR:-/data}
test -d "$VOLUME_DIR"           || die "no such directory: '$VOLUME_DIR'"

set_app_uidgid
if test -L $(which adduser); then # alpine
	addgroup -g $APP_GID app                        || die "addgroup failed"
	adduser -g app -s /bin/sh -D \
		-G app -u $APP_UID app                  || die "adduser failed"
else # debian
	addgroup --gid $APP_GID app                     || die "addgroup failed"
	adduser --gecos app --shell /bin/bash --disabled-password \
		--ingroup app --uid $APP_UID app        || die "adduser failed"
fi

chown -L app:app "$VOLUME_DIR"  || die "chown failed"

unset VOLUME_DIR APP_UID APP_GID
exec "$@"
